spring.application.name=cronos

# MongoDB Atlas por configurar
spring.mongodb.uri=mongodb+srv://cronos_admin:HEabMAFERJfAaE0p@cronos-cluster.ngv13rn.mongodb.net/?appName=cronos-cluster
spring.mongodb.database=cronos

# Gmail SMTP (JavaMail vía Spring Mail) //TODO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tucorreo@gmail.com
spring.mail.password=tu-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true