spring.application.name=cronos

spring.config.import=optional:file:./.env[.properties]

# MongoDB Atlas
spring.mongodb.uri=mongodb+srv://${MONGO_ATLAS_USER_NAME}:${MONGO_ATLAS_PASSWORD}@cronos-cluster.ngv13rn.mongodb.net/cronos?retryWrites=true&w=majority&appName=cronos-cluster
spring.mongodb.database=cronos
spring.data.mongodb.auto-index-creation=false

# Thymeleaf usa la carpeta /views
spring.thymeleaf.prefix=classpath:/views/
spring.thymeleaf.cache=false

# Correo SMTP
app.mail.service=${EMAIL_SERVICE:gmail}
app.mail.from=${EMAIL_FROM:${EMAIL_USER:}}
spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USER:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true