spring.application.name=cronos

# MongoDB Atlas por configurar //TODO
spring.data.mongodb.uri=mongodb+srv://usuario:password@cluster.mongodb.net/tributario

# Gmail SMTP (JavaMail vía Spring Mail) //TODO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tucorreo@gmail.com
spring.mail.password=tu-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true